# TEST 

In [1]:
import pandas as pd
import numpy as np
from Bio import SeqIO
import torch
from crossevopred.src.model.dummy_model import DummyModel
from crossevopred.src.model.dummy_trainer import DummyTrainer
from crossevopred.utils.data_processing_utils import *

fasta = "/home/luisasantus/Desktop/crg_cluster/data/CrossEvoPred/test/chr1.fa"
bed = "/home/luisasantus/Desktop/crg_cluster/data/CrossEvoPred/test/chr1.bed"
bedgraph = "/home/luisasantus/Desktop/crg_cluster/data/CrossEvoPred/test/chr1.bedgraph"
binsize = 5
training_dataset = "/home/luisasantus/Desktop/PROJECTS/CrossEvoPred/out/data/training_set/objects/chr1.pth"
config_file = "/home/luisasantus/Desktop/PROJECTS/CrossEvoPred/bin/crossevopred/config/test_config.yaml"
model_path = "/home/luisasantus/Desktop/PROJECTS/CrossEvoPred/out/models/model.pkl"
%load_ext autoreload
%autoreload 2

In [2]:
# retrain model 
model   = DummyModel()
trainer = DummyTrainer()
trainining_datatset_loader = torch.load(training_dataset)
print("Model initialized")
# Train the model
trainer.train(trainining_datatset_loader, config_file=config_file, model=model)

FileNotFoundError: [Errno 2] No such file or directory: '/home/luisasantus/Desktop/PROJECTS/CrossEvoPred/out/data/training_set/objects/chr1.pth'

In [130]:
trainining_datatset_loader.sequences.reshape(trainining_datatset_loader.sequences.size(0),-1).shape

torch.Size([2, 40])

In [131]:
sequences = get_sequences_from_bed(bed, fasta)

In [113]:
# compute length of all sequences
lengths = [len(seq) for seq in sequences]


In [114]:
test_sequence = dataset.sequences[0]
test_sequence

tensor([[1., 1., 0., 0., 0., 0., 1., 1., 0., 0.],
        [0., 0., 1., 1., 1., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [90]:
model(test_sequence.reshape(1,-1))

tensor([[nan]], grad_fn=<AddmmBackward0>)

In [135]:
model.evaluate(test_dataset_loader)

sequence  correlation
0  AACCCTAACC         -0.0
1  CTAACCCTAA         -0.0

In [11]:
from torch.utils.data import DataLoader
import torch 
from crossevopred.src.data.encoder import DNAEncoder
%load_ext autoreload
%autoreload 2

training_file = "../simulated/simulated"
training_dataset_file = training_file+ "_test_dataset.pt"
trainining_datatset_loader = DataLoader(torch.load(training_dataset_file), batch_size = 32, shuffle = True)


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [59]:
trainining_datatset_loader.dataset.sequences.shape

torch.Size([20, 4, 1000])

In [54]:
torch.flip(trainining_datatset_loader.dataset.labels[1:3], [0])

tensor([[3.2422, 3.3047, 3.2422, 3.2266, 3.2891, 3.2891, 3.3125],
        [3.2109, 3.2891, 3.2188, 3.2188, 3.2812, 3.1406, 3.3203]])

In [57]:

encoder = DNAEncoder()
one_hot_encoded_seq = encoder.encode_sequences(["AATC", "AAAA"])
# make it a tensor
one_hot_encoded_seq = torch.tensor(one_hot_encoded_seq)


In [58]:
one_hot_encoded_seq.shape

torch.Size([2, 4, 4])

In [64]:
rc = torch.flip(one_hot_encoded_seq, [1,2])
encoder.decode_one_hot(rc[1])

'TTTT'

In [11]:
reversed_tensor = tensor.flip(dims=(0,))
reversed_tensor

# now just invert a with t and c with g
# swap first row with the last row
reversed_tensor[0], reversed_tensor[-1] = reversed_tensor[-1], reversed_tensor[0]
# swap second row with the second last row
reversed_tensor[1], reversed_tensor[-2] = reversed_tensor[-2], reversed_tensor[1]



tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])

In [3]:

# Define the complement mapping
complement_mapping = torch.tensor([3, 2, 1, 0], dtype=torch.long)

# Reverse the tensor along the 0th dimension
reversed_tensor = transposed_tensor.flip(dims=(0,))

# Complement each nucleotide using the mapping
complemented_tensor = complement_mapping[reversed_tensor]

In [5]:
reversed_tensor

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]])